"""add a votes column to pitch class

Revision ID: 8b87196cb604
Revises: 13e07cd8fc15
Create Date: 2020-09-24 03:21:50.480915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b87196cb604'
down_revision = '13e07cd8fc15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('votes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'votes')
    # ### end Alembic commands ###
